# node.customer_let - Field Storage
langcode: en
status: true
dependencies:
  module:
    - node
    - options
id: node.customer_let
field_name: customer_let
entity_type: node
type: list_string
settings:
  allowed_values:
    -
      value: Oyj
      label: Oyj
    -
      value: Oy
      label: Oy
    -
      value: Ky
      label: Ky
    -
      value: Ay
      label: Ay
    -
      value: Tmi.
      label: Tmi.
  allowed_values_function: ''
module: options
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false

# node.customer_let - Field
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.customer_let
    - node.type.customer
  module:
    - options
id: node.customer.customer_let
field_name: customer_let
entity_type: node
bundle: customer
label: 'Customer Legal Entity Type (LET)'
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: list_string

# node.customer_let - Entity View Display
langcode: en
status: true
dependencies:
  config:
    - field.field.node.customer.body
    - field.field.node.customer.customer_coop_ended
    - field.field.node.customer.customer_coop_started
    - field.field.node.customer.customer_customer_localaddress
    - field.field.node.customer.customer_customername
    - field.field.node.customer.customer_let
    - field.field.node.customer.customer_postalcode
    - field.field.node.customer.customer_website
    - node.type.customer
  module:
    - datetime
    - link
    - options
    - user
_core:
  default_config_hash: ney74UmF4WfFRQt6aABzYM-RCApXgcp6BdvtlkkBYjw
id: node.customer.default
targetEntityType: node
bundle: customer
mode: default
content:
  customer_coop_ended:
    weight: 108
    label: 'above:'
    settings: {  }
    third_party_settings: {  }
    type: datetime_default
    region: content
  customer_coop_started:
    weight: 107
    label: 'above:'
    settings: {  }
    third_party_settings: {  }
    type: datetime_default
    region: content
  customer_customer_localaddress:
    weight: 105
    label: above
    settings: {  }
    third_party_settings: {  }
    type: string
    region: content
  customer_customername:
    weight: 101
    label: above
    settings: {  }
    third_party_settings: {  }
    type: string
    region: content
  customer_let:
    weight: 103
    label: above
    settings: {  }
    third_party_settings: {  }
    type: list_default
    region: content
  customer_postalcode:
    weight: 104
    label: above
    settings: {  }
    third_party_settings: {  }
    type: number_integer
    region: content
  customer_website:
    weight: 106
    label: above
    settings: {  }
    third_party_settings: {  }
    type: link
    region: content
  links:
    weight: 100
    region: content
hidden:
  body: true

# node.customer_let - Entity form Display
langcode: en
status: true
dependencies:
  config:
    - field.field.node.customer.body
    - field.field.node.customer.customer_coop_ended
    - field.field.node.customer.customer_coop_started
    - field.field.node.customer.customer_customer_localaddress
    - field.field.node.customer.customer_customername
    - field.field.node.customer.customer_let
    - field.field.node.customer.customer_postalcode
    - field.field.node.customer.customer_website
    - node.type.customer
  module:
    - datetime
    - link
    - path
id: node.customer.default
targetEntityType: node
bundle: customer
mode: default
content:
  created:
    type: datetime_timestamp
    weight: 2
    settings: {  }
    third_party_settings: {  }
    region: content
  customer_coop_ended:
    weight: 11
    settings: {  }
    third_party_settings: {  }
    type: datetime_default
    region: content
  customer_coop_started:
    weight: 10
    settings: {  }
    third_party_settings: {  }
    type: datetime_default
    region: content
  customer_customer_localaddress:
    weight: 8
    settings:
      size: 100
      placeholder: 'Local address'
    third_party_settings: {  }
    type: string_textfield
    region: content
  customer_customername:
    weight: 5
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: string_textfield
    region: content
  customer_let:
    weight: 121
    settings: {  }
    third_party_settings: {  }
    type: options_select
    region: content
  customer_postalcode:
    weight: 7
    settings:
      size: 5
      placeholder: 'Postal code'
    third_party_settings: {  }
    type: number
    region: content
  customer_website:
    weight: 9
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: link_default
    region: content
  path:
    type: path
    weight: 30
    region: content
    settings: {  }
    third_party_settings: {  }
  promote:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 15
    region: content
    third_party_settings: {  }
  status:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 120
    region: content
    third_party_settings: {  }
  sticky:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 16
    region: content
    third_party_settings: {  }
  title:
    type: string_textfield
    weight: -5
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 5
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    region: content
    third_party_settings: {  }
hidden:
  body: true